name: 🚀 New feature proposal
description: Propose a new feature request
title: "[feature] "
labels: [feature]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature enhancement report!

  - type: textarea
    id: feature-description
    attributes:
      label: Clear and concise description of your idea
      description: "A clear and concise description of what the feature would do. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
    validations:
      required: true

  - type: textarea
    id: helpful-description
    attributes:
      label: Describe how the idea would be helpful
      description: "A clear and concise description of how the feature would be helpful to users."
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
        - label: Maintain a respectful, civil, open-minded, and friendly attitude in all interactions.
          required: true
