name: 👀 Typo / Grammar fix
description: You can just go ahead and send a PR! Thank you!
title: "[Typo] "
labels: [typo]

body:
  - type: markdown
    attributes:
      value: |
        ## PR Welcome!

        If the typo / grammar issue is trivial and straightforward, you can help by directly sending a pull request!
        If you spot multiple of them, we suggest combining them into a single PR. Thanks!

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the typo here.
      placeholder: Additional context information
