name: 🤔 Ask question
description: Consider using discussions for simple usage questions instead of issues.
title: "[Ask] "
labels: [ask]

body:
  - type: markdown
    attributes:
      value: |
        ## Kindly note

        We encourage you to use Github Discussions instead of asking about usage in issues.
        It's preferable to issues larger matters here.

  - type: textarea
    id: question-description
    attributes:
      label: Describe your question
      description: A clear and concise description is welcome.
      placeholder: Describe question
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Maintain a respectful, civil, open-minded, and friendly attitude in all interactions.
          required: true
